### ISSUE TITLE
独显RX460支持咨询

### ISSUE THREAD

**Issue by beta4better** [ahuinee/OpenCore-EFI#1]
咨询一个问题哈，请问有针对独显做屏蔽吗？
我有一个RX460的显卡，在H370M的板子上是可以在黑苹果下免驱使用的，但是插到B460M上用你这个EFI独显就没输出了，显示输出走的是核显。

有时间的话帮给看下，谢了。

**Comment by ahuinee** [comment]
> 咨询一个问题哈，请问有针对独显做屏蔽吗？ 我有一个RX460的显卡，在H370M的板子上是可以在黑苹果下免驱使用的，但是插到B460M上用你这个EFI独显就没输出了，显示输出走的是核显。
> 
> 有时间的话帮给看下，谢了。

好像是的，我明天改下，给你单独开个分支你试一下。

**Comment by ahuinee** [comment]
> 咨询一个问题哈，请问有针对独显做屏蔽吗？ 我有一个RX460的显卡，在H370M的板子上是可以在黑苹果下免驱使用的，但是插到B460M上用你这个EFI独显就没输出了，显示输出走的是核显。
> 
> 有时间的话帮给看下，谢了。

**Comment by ahuinee** [comment]
> 咨询一个问题哈，请问有针对独显做屏蔽吗？ 我有一个RX460的显卡，在H370M的板子上是可以在黑苹果下免驱使用的，但是插到B460M上用你这个EFI独显就没输出了，显示输出走的是核显。
> 
> 有时间的话帮给看下，谢了

你切换到 feature/unlock-more-gpu分支 尝试一下

**Comment by beta4better** [comment]
晚上回去试，等我更新哈

**Comment by beta4better** [comment]
-wegnoegpu

是把这个参数去掉吗？是的话我就直接改掉，不用替换三码了。

**Comment by beta4better** [comment]
去掉-wegnoegpu 就可以使用独立显卡了
