### ISSUE TITLE
USB端口定制

### ISSUE THREAD

**Issue by beta4better** [ahuinee/OpenCore-EFI#2]
再请问一个问题，看是否有遇到。
我在用无线鼠标的时候会出现延迟卡顿的情况，尤其是在插入其他USB设备的时候更加明显，但是用有线鼠标就没这个问题，目前还不知道是啥问题。

**Comment by ahuinee** [comment]
> 再请问一个问题，看是否有遇到。 我在用无线鼠标的时候会出现延迟卡顿的情况，尤其是在插入其他USB设备的时候更加明显，但是用有线鼠标就没这个问题，目前还不知道是啥问题。

我自己使用的鼠标GPW和G304和有线102都没有出现卡顿的情况。
理论上来说只有USB能通信卡顿问题应该是传输问题或者无线鼠标驱动问题，跟硬件驱动应该没关系。
